version: '3.8'
services:
  picture-engraver:
    build: .
    image: pixelplanet5/picture-engraver:latest
    container_name: picture-engraver
    ports:
      - "3002:80"
    restart: unless-stopped
